
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
// специально оставили синхронным
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_SERVICE = 'CHANGE_SERVICE';
export const FETCH_CHANGE_FAILURE = 'FETCH_CHANGE_FAILURE';
export const FETCH_CHANGE_SUCCESS = 'FETCH_CHANGE_SUCCESS';
export const SAVE_CHANGE_SUCCESS = 'SAVE_CHANGE_SUCCESS';
export const SAVE_CHANGE_FAILURE = 'SAVE_CHANGE_FAILURE';
export const CHANGE_SERVICE_REQUEST = 'CHANGE_SERVICE_REQUEST';